import type { Metadata } from "next";
import { Inter, Familjen_Grotesk, Instrument_Serif } from "next/font/google";

import "./globals.css";
import Header from "@/components/layout/header/header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const familjenGrotesk = Familjen_Grotesk({
  variable: "--font-familjen",
  subsets: ["latin"],
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sr-Latn">
      <body
        className={`${inter.variable} ${familjenGrotesk.variable} ${instrumentSerif.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
